### ISSUE TITLE
Convention is to place `require` and other such directives inside the module

### ISSUE THREAD

**Issue by lee-dohm** [vaibhav-y/parascoin#1]
https://github.com/vaibhav-y/parascoin/blob/dfb8af80d85e56f72b5a6c48f10db84f21b719f0/lib/cli.ex#L1

Even though the convention is to only have one module per file and there's probably little difference between placing the `require` outside the `Paras.CLI` module and inside it, the convention is to place [`require`, `alias`, and `import` directives and the `use` macro](https://elixir-lang.org/getting-started/alias-require-and-import.html) inside [the module to which it is intended to apply.](https://github.com/elixir-lang/elixir/blob/89867a90adcb84b4c71a9c0897c7997776e76b84/lib/logger/lib/logger/error_handler.ex#L6)

**Comment by envp** [comment]
I see, I wasn't aware of that. Would you say that [this style guide](https://github.com/christopheradams/elixir_style_guide), is a safe bet to follow for starting off with best practices?

Corrected in 01252f9349945c24e2d7cad14fcba61f76bb5c3d , thanks!
